require('settings')
require('packer-config')
require('colorscheme-config.nightfox')
require('nvim-tree-config')
require('mappings')
require('lsp-config.language-servers')
require('lsp-config.cmp-config')
